[package]
name = "nes-emulator"
version = "0.1.0"
authors = ["Lewis <lewisgiannelli@hotmail.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
